export const SET_IPP_MARKER = 'SET_IPP_MARKER';
export const CLEAR_IPP_MARKER = 'CLEAR_IPP_MARKER';
export const SET_DIRECTION_MARKER = 'SET_DIRECTION_MARKER';
export const CLEAR_DIRECTION_MARKER = 'CLEAR_DIRECTION_MARKER';
export const SET_BEHAVIOR = 'SET_BEHAVIOR';
export const SET_MAP_CENTER = 'SET_MAP_CENTER';
